version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data:/app/data
    networks:
      - webnet

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - backend

networks:
  webnet:
