version: '3.8'

services:
  container_1:
    build: .
    container_name: container_1
    volumes:
      - demo_volume:/data

  container_2:
    build: .
    container_name: container_2
    volumes:
      - demo_volume:/data

  container_3:
    image: alpine
    container_name: container_3
    command: ["sh", "-c", "ls /data"]
    volumes:
      - demo_volume:/data

volumes:
  demo_volume:
